name: translator_test

services:
  postgres_test:
    container_name: translator_database_test
    image: postgres:latest
    expose:
      - ${DATABASE_PORT}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    env_file:
      - .env.test
    volumes:
      - translator_database_data_test:/var/lib/postgresql/data
      - ./.docker/postgres/potgresql.conf:/etc/postgresql.conf
    command: -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped
    networks:
      - translator_local_test

  server_test:
    container_name: translator_server_test
    image: server-test:0.0.1-test
    build:
      context: .
      dockerfile: ./.docker/server/Dockerfile.ci
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres_test
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    restart: always
    networks:
      - translator_local_test
    env_file:
      - .env.test

volumes:
  translator_database_data_test:

networks:
  translator_local_test:
    driver: bridge
